CREATE TABLE "Region" (
  "region_id" SERIAL PRIMARY KEY,
  "region_name" VARCHAR(255) UNIQUE
);

CREATE TABLE "Country" (
  "country_id" SERIAL PRIMARY KEY,
  "region_id" INTEGER,
  "country_name" VARCHAR(255) UNIQUE
);

CREATE TABLE "State" (
  "state_id" SERIAL PRIMARY KEY,
  "country_id" INTEGER,
  "state_name" VARCHAR(255) UNIQUE
);

CREATE TABLE "City" (
  "city_id" SERIAL PRIMARY KEY,
  "state_id" INTEGER,
  "city_name" VARCHAR(255) UNIQUE
);

CREATE TABLE "Warehouse" (
  "warehouse_id" SERIAL PRIMARY KEY,
  "city_id" INTEGER,
  "warehouse_address" VARCHAR(255),
  "warehouse_name" VARCHAR(255),
  "postal_code" VARCHAR(20)
);

CREATE TABLE "Employee" (
  "employee_id" SERIAL PRIMARY KEY,
  "warehouse_id" INTEGER,
  "employee_name" VARCHAR(255),
  "employee_email" VARCHAR(255) UNIQUE,
  "employee_phone" VARCHAR(20),
  "employee_hire_date" DATE,
  "employee_job_title" VARCHAR(100)
);

CREATE TABLE "Category" (
  "category_id" SERIAL PRIMARY KEY,
  "category_name" VARCHAR(255) UNIQUE
);

CREATE TABLE "Product" (
  "product_id" SERIAL PRIMARY KEY,
  "category_id" INTEGER,
  "product_name" VARCHAR(255),
  "product_description" VARCHAR(255),
  "product_standard_cost" NUMERIC,
  "product_list_price" NUMERIC,
  "profit" NUMERIC
);

CREATE TABLE "Customer" (
  "customer_id" SERIAL PRIMARY KEY,
  "customer_name" VARCHAR(255),
  "customer_address" VARCHAR(255),
  "customer_credit_limit" NUMERIC,
  "customer_email" VARCHAR(255) UNIQUE,
  "customer_phone" VARCHAR(20)
);

CREATE TABLE "OrderTable" (
  "order_id" SERIAL PRIMARY KEY,
  "customer_id" INTEGER,
  "order_date" DATE,
  "employee_id" INT
);

CREATE TABLE "OrderItem" (
  "order_item_id" SERIAL PRIMARY KEY,
  "order_id" INTEGER,
  "product_id" INTEGER,
  "order_item_quantity" INTEGER,
  "per_unit_price" NUMERIC,
  "total_item_quantity" INTEGER,
  "product_shipping_status" VARCHAR(100)
);

CREATE TABLE "Inventory" (
  "inventory_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" INT,
  "stock_level" INT,
  "reorder_threshold" INT
);

CREATE TABLE "reorder_requests" (
  "request_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int,
  "reorder_quantity" int,
  "request_date" date,
  "status" varchar
);

ALTER TABLE "Country" ADD FOREIGN KEY ("region_id") REFERENCES "Region" ("region_id");

ALTER TABLE "State" ADD FOREIGN KEY ("country_id") REFERENCES "Country" ("country_id");

ALTER TABLE "City" ADD FOREIGN KEY ("state_id") REFERENCES "State" ("state_id");

ALTER TABLE "Warehouse" ADD FOREIGN KEY ("city_id") REFERENCES "City" ("city_id");

ALTER TABLE "Employee" ADD FOREIGN KEY ("warehouse_id") REFERENCES "Warehouse" ("warehouse_id");

ALTER TABLE "Product" ADD FOREIGN KEY ("category_id") REFERENCES "Category" ("category_id");

ALTER TABLE "OrderTable" ADD FOREIGN KEY ("customer_id") REFERENCES "Customer" ("customer_id");

ALTER TABLE "OrderTable" ADD FOREIGN KEY ("employee_id") REFERENCES "Employee" ("employee_id");

ALTER TABLE "OrderItem" ADD FOREIGN KEY ("order_id") REFERENCES "OrderTable" ("order_id");

ALTER TABLE "OrderItem" ADD FOREIGN KEY ("product_id") REFERENCES "Product" ("product_id");

ALTER TABLE "Inventory" ADD FOREIGN KEY ("product_id") REFERENCES "Product" ("product_id");

ALTER TABLE "reorder_requests" ADD FOREIGN KEY ("product_id") REFERENCES "Product" ("product_id");
